### ISSUE TITLE
Home Page "Book Now" button's login popup not functioning

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#52]
![441374490_1104191070639712_7932326827545217011_n](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/07b95d21-3a9a-458c-a5b5-828000c6478b)
When user tries to login after clicking on "Book Now" button, the logged in homepage is not shown instead, it is redirected to the same login/signup homepage.

**Comment by Nileena106** [comment]
The issue was created due to an action URL missing in the form within login popup. I added the missing link {% url 'login' %} in the login form. Now, when user submits the login form from the popup window, the form data will be handled by the login authentication view just like logging in from the regular login page.

![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/118924024/2fcc1b33-ac70-4212-a358-0c949a652527)
