### ISSUE TITLE
Logical Error when booking car

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#53]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/b152e403-9aec-404e-bc94-d624cbb1c5c2)
User can still book the car even when the start date is today and the end date is the day before yesterday.

**Comment by Adityaarai** [comment]
The issue was created due to lack of logical statements regarding the booking date. This was fixed by adding some basic logical statements to check the booking date. The added code checks the date and sends a error message if some thing is wrong otherwise the booking will proceed as normal.

Implemented code
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/3a5f5dfb-79c1-42e7-afa0-cde205ba7258)

Error handling
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/7d05d38d-cc80-435f-8236-ad99cbe7ead3)
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/ebc3b06f-9442-42d1-b5b0-cb15b69c9beb)
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/73c795f8-0998-4d9c-854a-63b1e1844344)

Success message
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/e6a91aed-9228-4596-80c3-4db29f3da447)

**Comment by Adityaarai** [comment]
The issue was created due to lack of logical statements regarding the booking date. This was fixed by adding some basic logical statements to check the booking date. The added code checks the date and sends a error message if some thing is wrong otherwise the booking will proceed as normal.

Implemented code
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/3a5f5dfb-79c1-42e7-afa0-cde205ba7258)

Error handling
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/7d05d38d-cc80-435f-8236-ad99cbe7ead3)
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/ebc3b06f-9442-42d1-b5b0-cb15b69c9beb)
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/73c795f8-0998-4d9c-854a-63b1e1844344)

Success message
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/e6a91aed-9228-4596-80c3-4db29f3da447)
