### ISSUE TITLE
Shows error when viewing profile

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#57]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/e42b7638-9c71-42b7-aacc-724a1c552c85)
When user logs in and go to 'My Profile' page, it shows an error instead of showing their profile page to edit their profile, view their added cars, or bookings history.

**Comment by Nileena106** [comment]
The error was shown because in the code inside 'My Profile', 'My Bookings' section, 'if' statement was used to check if there are any pending bookings available. However, the else statement was missing. Hence, I added the missing code of else tag and resolved this bug issue.

![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/118924024/5e42b94a-ac33-456b-898c-f0b5f8c6921f)
