### ISSUE TITLE
Car details "Back" button not working!

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#63]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/13702f4c-d41d-494e-9155-388ea353756e)
When User wants to go back to "Book cars" section it does not redirect to to that section instead shows message.

**Comment by Adityaarai** [comment]
This error was caused due to the back button still being in the form tag. Since the form type is POST, the button was redirecting to the orders view directly, disregarding its anchor tag. 
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/7cc9d2ae-f3c6-4ac7-893c-b91c16e8a477)
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/d51e2087-2ab9-410b-869b-340b899aa428)

This was solved simply by removing the back button from the form tag. 
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119116034/565ed5fa-06eb-453a-83c4-5fd4a6221b36)
