### ISSUE TITLE
Error shown after user clicked 'OK' button upon successful payment message

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#76]
![440794572_991399302041987_7577274691142456340_n](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/ecab00ee-7d8c-4904-97ef-3dc81a0e1b1b)
When user clicks on 'Payment' button and enters their payment information to complete their payment, the successful payment alert message is shown. However, when clicked 'OK' on that message, this kind of error is shown.

**Comment by Nileena106** [comment]
This error was shown in payment.html file because upon successful payment, when user clicked 'OK' button on the alert message, I had written code to redirect them to user profile page. However, before, in my code, the URL to navigate user to their profile page was 'user/profile'. However, the actual URL for user_profile is '/user/profile'. So, I corrected that URL and fixed this issue.

![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/118924024/7a4b5fc5-759c-4cd1-bf3c-072625b03507)
