### ISSUE TITLE
Unable to access my profile 

### ISSUE THREAD

**Issue by PrajwolGithub** [Adityaarai/VROOM-Car-Rental#88]
![image_2024-05-16_121743553](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144331/d086fde8-975d-4e70-a76b-f90fff492c4b)
Not able to view the profile details Clicking on my profile causes a FieldError to occur.

**Comment by Nileena106** [comment]
This issue was caused in 'My Profile' page due to some changes made in CarOrder model. I had used 'rentee_email' column to fetch data from CarOrder model database. However, due to changes made in that database, 'rentee_email' was removed and 'rentee' was used. So, I fixed that issue by changing 'rentee_email' to 'rentee' for fetching data from that CarOrder model in my authviews.py file.

![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/118924024/0ca77efc-9c5a-4815-8c98-57432c0b4723)
