### ISSUE TITLE
Error page when user tries to book the car that is booked

### ISSUE THREAD

**Issue by tenzintsongi** [Adityaarai/VROOM-Car-Rental#99]
![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/119144229/ae316f4d-23f9-4949-b769-26917928030a)
When user tries to pre-order the booked car using end date before start date, it should display an error message but it is showing this error instead.

**Comment by Nileena106** [comment]
This issue was caused because the 'car_order.end_date' was a 'datetime' object, while 'start_date_obj' was a 'date' object. So, while comparing them, the error was raised because the comparison can only be made between the same type. So, to fix this, I converted 'car_order.end_date' to a 'date' object for comparing it with 'start_date_obj' using 'car_order.end_date.date()' and fixed this issue.

![image](https://github.com/Adityaarai/VROOM-Car-Rental/assets/118924024/d8d7089f-4b94-439c-8336-ec184e31ed2b)
